[book]
title = "Lio Qing's Blogs"
authors = ["LioQing"]
language = "en"

[output.html]
no-section-label = true
# additional-css = ["lioqing-highlight.css"]

[output.html.fold]
enable = true
level = 0
